blank_issues_enabled: true
contact_links:
  - name: Usage questions
    url: https://github.com/{{cookiecutter.gh_user}}/{{cookiecutter.repo_name}}/discussions
    about: Ask questions and discuss with other {{cookiecutter.package_name}} community members
